
import { VehicleProps } from '@/components/VehicleCard';

export const mockVehicles: VehicleProps[] = [
  {
    id: 'v1',
    name: 'Toyota Land Cruiser',
    type: '4x4',
    pricePerDay: 89,
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf',
    features: ['Climatisation', 'GPS', 'Porte-bagages', '4x4', 'Bluetooth', 'Ports USB'],
    availability: true,
  },
  {
    id: 'v2',
    name: 'Yamaha TW200',
    type: 'motorcycle',
    pricePerDay: 45,
    seats: 2,
    transmission: 'Manual',
    fuelType: 'Essence',
    image: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39',
    features: ['Casque inclus', 'Sacoches', 'Capacité tout-terrain', 'Économe en carburant'],
    availability: true,
  },
  {
    id: 'v3',
    name: 'BRP Can-Am Outlander',
    type: 'quad',
    pricePerDay: 65,
    seats: 1,
    transmission: 'Automatic',
    fuelType: 'Essence',
    image: 'https://images.unsplash.com/photo-1628985816814-b5ce00832b6a',
    features: ['Casque inclus', 'Coffre de rangement', '4x4', 'Garde au sol élevée'],
    availability: true,
  },
  {
    id: 'v4',
    name: 'Toyota Corolla',
    type: 'car',
    pricePerDay: 55,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Essence',
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588',
    features: ['Climatisation', 'Bluetooth', 'Économe en carburant', 'Ports USB'],
    availability: true,
  },
  {
    id: 'v5',
    name: 'Mitsubishi Pajero',
    type: '4x4',
    pricePerDay: 85,
    seats: 7,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70',
    features: ['Climatisation', 'GPS', 'Porte-bagages', '4x4', 'Bluetooth'],
    availability: true,
  },
  {
    id: 'v6',
    name: 'Peugeot 208',
    type: 'car',
    pricePerDay: 40,
    seats: 5,
    transmission: 'Manual',
    fuelType: 'Essence',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d',
    features: ['Climatisation', 'Bluetooth', 'Économe en carburant'],
    availability: true,
  },
];
