
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huvhudegtnlikydssvhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1dmh1ZGVndG5saWt5ZHNzdmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDE2NTcsImV4cCI6MjA2MDA3NzY1N30.yLnaCMbaZDZNYA6lULohkdmu9dDLc_Hquz6rdT21-2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
